In [10]:
import pandas as  pd

In [12]:
df = pd.read_csv(r'C:\Users\Srivally\Downloads\Cantellat Internship\FIN_MAR12_MAR21_DATA.txt',sep="|")

In [13]:
display(df)

,ca_finance1_cocode,ca_company_name,ca_finance1_year,ca_ann_rep_months,ca_fs_format,ca_total_income,ca_sales,ca_total_interest_exp,ca_pat,ca_pbdita,ca_net_worth,ca_debt,ca_total_assets,ca_net_fixed_assets,ca_gross_fixed_assets
0,11,20 MICRONS LTD.,2012-03-31,12,IGAAP,3095.5,3073.2,135.3,110.4,399.2,578.3,1586.8,2784.9,842.8,1275.6
1,11,20 MICRONS LTD.,2013-03-31,12,IGAAP,3278.9,3240.1,209.3,47.8,439.1,692.1,1648.4,3057.6,1518.8,2029.6
2,11,20 MICRONS LTD.,2014-03-31,12,IGAAP,3452.5,3417.7,242.2,-23.1,332.6,741.7,1767.2,3425.0,1576.4,2183.3
3,11,20 MICRONS LTD.,2015-03-31,12,IGAAP,3763.6,3719.0,241.6,-24.9,350.7,711.5,1665.4,3498.9,1513.2,2219.5
4,11,20 MICRONS LTD.,2016-03-31,12,IGAAP,3784.4,3750.4,231.5,110.6,493.1,879.2,1634.2,3532.9,1511.7,2314.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17042,656295,C W D LTD.,2020-03-31,12,IGAAP,30.3,30.2,4.9,5.5,10.8,-22.0,57.0,41.8,3.3,4.3
17043,656295,C W D LTD.,2021-03-31,12,IGAAP,34.2,33.9,4.8,13.7,13.6,16.1,43.2,77.5,12.6,15.4
17044,656548,WHERRELZ I T SOLUTIONS LTD.,2019-03-31,12,IGAAP,1.9,1.9,NaN,0.2,0.3,0.8,NaN,0.8,0.1,0.1
17045,656548,WHERRELZ I T SOLUTIONS LTD.,2020-03-31,12,IGAAP,2.2,2.2,NaN,0.2,0.4,0.6,0.1,0.8,0.2,0.5
17046,656548,WHERRELZ I T SOLUTIONS LTD.,2021-03-31,12,IGAAP,2.0,2.0,NaN,0.2,0.4,0.8,NaN,0.9,0.2,0.6

In [14]:
df = pd.read_csv(r'C:\Users\Srivally\Downloads\Cantellat Internship\RPT_MAR12_MAR21_DATA.txt',sep="|")

In [15]:
display(df)

,rpt_cocode,company_name,rpt_date,rpt_party_type,related_party_type_mst,rpt_party_name,rpt_income,rpt_goods_n_services_inc,rpt_operating_inc,rpt_rent_inc,...,rpt_not_available,rpt_borr_unclass,rpt_dividend_unclass,rpt_interest_unclass,rpt_rent_unclass,rpt_services_unclass,rpt_max_amt_payable,rpt_max_amt_recv,rpt_loc_standby_loc,rpt_other_unclass
0,11,20 MICRONS LTD.,2012-03-31,200,Key Personnel,A C PARIKH,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11,20 MICRONS LTD.,2012-03-31,200,Key Personnel,ATIL C PARIKH,21.2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11,20 MICRONS LTD.,2012-03-31,200,Key Personnel,All Key Personnel,63.7,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11,20 MICRONS LTD.,2012-03-31,200,Key Personnel,C S PARIKH,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,20 MICRONS LTD.,2012-03-31,200,Key Personnel,Key Personnel - Names Undisclosed,42.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
877290,658574,S P REFRACTORIES LTD.,2021-03-31,200,Key Personnel,SHWETA KALE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877291,658574,S P REFRACTORIES LTD.,2021-03-31,9999,All Party Types,All Party Types,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877292,659294,EKENNIS SOFTWARE SERVICE LTD.,2021-03-31,200,Key Personnel,All Key Personnel,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877293,659294,EKENNIS SOFTWARE SERVICE LTD.,2021-03-31,200,Key Personnel,MANISHA SHARMA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877294,659294,EKENNIS SOFTWARE SERVICE LTD.,2021-03-31,9999,All Party Types,All Party Types,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df = pd.read_csv(r'C:\Users\Srivally\Downloads\Cantellat Internship\BoD_MAR12_MAR21_DATA.txt',sep="|")

In [17]:
display(df)

,co_code,company_name,directors_name,corpdiro_date,committee_name,corpdiro_din,designation_full_name,category,board_meetings_attended,salary,...,indep_non_indep_category,no_of_oth_cos_chairperson,has_resigned,no_of_committee_pos_held,has_retired,last_agm_attended,appointment_date,resignation_date,no_of_oth_cos_director,corpdiro_desig_seqno
0,11,20 MICRONS LTD.,ATIL C PARIKH,2012-03-31,Board of directors,41712.0,Joint Managing Director,Executive-Non-independent,4.0,2010000.0,...,Non-independent,NaN,NaN,3.0,NaN,Y,NaN,NaN,2.0,4.0
1,11,20 MICRONS LTD.,ATUL H PATEL,2012-03-31,Board of directors,9587.0,Director,Non-executive-Independent,4.0,NaN,...,Independent,NaN,NaN,3.0,NaN,NaN,NaN,NaN,10.0,9.0
2,11,20 MICRONS LTD.,CHANDRESH PARIKH,2012-03-31,Board of directors,41584.0,Chairperson & Managing Director,Executive-Non-independent,7.0,3240000.0,...,Non-independent,NaN,NaN,8.0,NaN,Y,NaN,NaN,5.0,3.0
3,11,20 MICRONS LTD.,MIHIR JOSHI,2012-03-31,Board of directors,NaN,Director (GVFL),Non-executive-Non-independent,2.0,NaN,...,Non-independent,NaN,Y,NaN,NaN,NaN,NaN,2011-10-22,NaN,8.0
4,11,20 MICRONS LTD.,MUNISH MOHAN,2012-03-31,Board of directors,NaN,Director (IDBI),Non-executive-Non-independent,0.0,NaN,...,Non-independent,NaN,Y,NaN,NaN,NaN,NaN,2011-04-29,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
933135,659714,EVOQ REMEDIES LTD.,KOMALBEN PATEL VASHISTHBHAI (MRS.),2020-03-31,Board of directors,NaN,Director,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2019-04-12,NaN,NaN,9.0
933136,659714,EVOQ REMEDIES LTD.,BHUMISHTH NARENDRABHAI PATEL,2021-03-31,Board of directors,2516641.0,Director,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
933137,659714,EVOQ REMEDIES LTD.,KOMALBEN PATEL VASHISTHBHAI (MRS.),2021-03-31,Board of directors,NaN,Director,NaN,NaN,NaN,...,NaN,NaN,Y,NaN,NaN,NaN,NaN,2020-06-17,NaN,9.0
933138,659714,EVOQ REMEDIES LTD.,PAYAL N PATEL,2021-03-31,Board of directors,5300011.0,Director,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2020-06-17,NaN,NaN,9.0
933139,659714,EVOQ REMEDIES LTD.,SHASHIKANT V SHARMA,2021-03-31,Board of directors,NaN,Additional Director,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-06,NaN,NaN,9.0